# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 03:37
from __future__ import unicode_literals

import MedicalForms.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20160822_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('check_in', models.BooleanField(default=False)),
                ('reasons', MedicalForms.utils.MyTextField(blank=True)),
                ('symptoms', MedicalForms.utils.MyTextField(blank=True)),
                ('doctors_note', MedicalForms.utils.MyTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('name', MedicalForms.utils.MyCharField(blank=True, max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', MedicalForms.utils.MyCharField(blank=True, max_length=20)),
                ('description', MedicalForms.utils.MyTextField(blank=True)),
                ('city', MedicalForms.utils.MyCharField(blank=True, max_length=20)),
                ('address', MedicalForms.utils.MyCharField(blank=True, max_length=200)),
                ('postal_code', MedicalForms.utils.MyCharField(blank=True, max_length=10)),
                ('start_time_mon', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('end_time_mon', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('start_time_tue', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('end_time_tue', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('start_time_wed', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('end_time_wed', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('start_time_thurs', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('end_time_thurs', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('start_time_fri', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('end_time_fri', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('start_time_sat', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('end_time_sat', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('start_time_sun', MedicalForms.utils.MyTimeField(blank=True, null=True)),
                ('end_time_sun', MedicalForms.utils.MyTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('HCAI', MedicalForms.utils.MyCharField(blank=True, max_length=30)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MedicalAppointments.Clinic')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('specialty', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('image_url', models.CharField(default=b'img/features/featured-2.jpg', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_form', models.FileField(upload_to=b'forms')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('transportation_need', MedicalForms.utils.MySelectField(blank=True, default=b'Regular', max_length=30)),
                ('past_medications', MedicalForms.utils.MyCharField(blank=True, max_length=200)),
                ('current_medications', MedicalForms.utils.MyCharField(blank=True, max_length=200)),
                ('height', MedicalForms.utils.MyCharField(blank=True, max_length=30)),
                ('weight', MedicalForms.utils.MyCharField(blank=True, max_length=30)),
                ('smoking', MedicalForms.utils.MyNullBooleanField()),
                ('alcohol', MedicalForms.utils.MyNullBooleanField()),
                ('marijuana', MedicalForms.utils.MyNullBooleanField()),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MedicalAppointments.Clinic')),
            ],
        ),
        migrations.AddField(
            model_name='newforms',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointments.Patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointments.DoctorSpecialty'),
        ),
        migrations.AddField(
            model_name='booking',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointments.Clinic'),
        ),
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointments.Doctor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicalAppointments.Patient'),
        ),
    ]
