# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import MedicalForms.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedicalAppointments', '0003_remove_clinic_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentHistory',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('description_and_location', MedicalForms.utils.MyTextField(blank=True)),
                ('road_condition', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('anticipation_of_accident', MedicalForms.utils.MyNullBooleanField()),
                ('time_of_the_day', MedicalForms.utils.MyTimeField(null=True, blank=True)),
                ('patient_vehicle', MedicalForms.utils.MyCharField(max_length=30, blank=True)),
                ('patient_vehicle_speed', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('other_vehicle', MedicalForms.utils.MyCharField(max_length=30, blank=True)),
                ('other_vehicle_speed', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('collision_type', MedicalForms.utils.MySelectField(max_length=30, blank=True)),
                ('vehicle_towed', MedicalForms.utils.MyNullBooleanField()),
                ('impact_with_objects', MedicalForms.utils.MyNullBooleanField()),
                ('impact_with_objects_detail', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('exit_from_vehicle', MedicalForms.utils.MySelectField(max_length=30, blank=True)),
                ('loss_of_consciousness', MedicalForms.utils.MyNullBooleanField()),
                ('safety_equipment', MedicalForms.utils.MyNullBooleanField()),
                ('airbag_deployed', MedicalForms.utils.MyNullBooleanField()),
                ('driver', MedicalForms.utils.MyNullBooleanField()),
                ('dominant_hand', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('headache', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('dizziness', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('chest_pain', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('nausea_voimit', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('bleeding', MedicalForms.utils.MyCharField(max_length=30, blank=True)),
                ('head_neck', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('back', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('shoulders', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('legs', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('arms', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('other', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('hospitalized', MedicalForms.utils.MyNullBooleanField()),
                ('hospitalized_detail', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('transportation', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('examination_date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('examination_other', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('treatment', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('seen_doctor', MedicalForms.utils.MyNullBooleanField()),
                ('doctor_name', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('doctor_date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('treatment_recommendation', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcuteConcussionEvaluation',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('dob', MedicalForms.utils.MyDateField(null=True, blank=True)),
                ('date_of_injury', MedicalForms.utils.MyDateField(null=True, blank=True)),
                ('time_of_injury', MedicalForms.utils.MyTimeField(null=True, blank=True)),
                ('reporter', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('injury_description', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('evidence_of_blow', MedicalForms.utils.MyNullBooleanField()),
                ('evidence_of_cranial_injury', MedicalForms.utils.MyNullBooleanField()),
                ('cause', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('sports_specify', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('others_specify', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('amnesia_before', MedicalForms.utils.MyNullBooleanField()),
                ('amnesia_before_duration', MedicalForms.utils.MyCharField(max_length=10, blank=True)),
                ('amnesia_after', MedicalForms.utils.MyNullBooleanField()),
                ('amnesia_after_duration', MedicalForms.utils.MyCharField(max_length=10, blank=True)),
                ('lost_of_consciousness', MedicalForms.utils.MyNullBooleanField()),
                ('lost_of_consciousness_duration', MedicalForms.utils.MyCharField(max_length=10, blank=True)),
                ('seizure', MedicalForms.utils.MyNullBooleanField()),
                ('seizure_detail', MedicalForms.utils.MyCharField(max_length=10, blank=True)),
                ('headache', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('nausea', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('vomiting', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('balance_problems', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('dizziness', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('visual_problems', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('fatigue', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('sensitivity_to_light', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('sensitivity_to_noise', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('numbness_and_tingling', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('physical_total', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('foggy', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('slow_down', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('difficulty_concentrating', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('difficulty_remembering', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('cognitive_total', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('irritability', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('sadness', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('more_emotional', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('nervousness', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('emotional_total', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('drowsiness', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('sleeping_less', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('sleeping_more', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('trouble_falling_asleep', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('sleep_total', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('all_total', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('excertion_physical', MedicalForms.utils.MyNullBooleanField()),
                ('excertion_cognitive', MedicalForms.utils.MyNullBooleanField()),
                ('overall_rating', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('concussion_history', MedicalForms.utils.MyNullBooleanField()),
                ('previous_number', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('longest_duration', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('less_force_caused_reinjury', MedicalForms.utils.MyNullBooleanField()),
                ('headache_history', MedicalForms.utils.MyNullBooleanField()),
                ('prior_treatment', MedicalForms.utils.MyNullBooleanField()),
                ('history_of_migraine', MedicalForms.utils.MyNullBooleanField()),
                ('personal_family', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('learning_disabilities', MedicalForms.utils.MyNullBooleanField()),
                ('attention_deficit', MedicalForms.utils.MyNullBooleanField()),
                ('other_developmental', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('anxiety', MedicalForms.utils.MyNullBooleanField()),
                ('depression', MedicalForms.utils.MyNullBooleanField()),
                ('sleep_disorder', MedicalForms.utils.MyNullBooleanField()),
                ('other_psychiatric', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('list_other_disorders', MedicalForms.utils.MyCharField(max_length=200, blank=True)),
                ('follow_up', MedicalForms.utils.MySelectField(max_length=30, blank=True)),
                ('refferal_others', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('completed_date', MedicalForms.utils.MyDateField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AggravatedByHeadache',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AggravatedByOthers',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AggravatedByPeripheralJoint',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArmsLeftRight',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('today_date', MedicalForms.utils.MyDateTimeField(auto_now_add=True, null=True)),
                ('date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('visit_number', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('clinician', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('subjective_choices', MedicalForms.utils.MySelectField(max_length=15, blank=True)),
                ('subjective_description', MedicalForms.utils.MyTextField(blank=True)),
                ('assessment', MedicalForms.utils.MyTextField(blank=True)),
                ('objective', MedicalForms.utils.MyTextField(blank=True)),
                ('smt', MedicalForms.utils.MyTextField(blank=True)),
                ('stt', MedicalForms.utils.MyTextField(blank=True)),
                ('cardio', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('stretch', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('strength', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('ifc', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('u_s', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('heat', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('ice', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('ohter', MedicalForms.utils.MyTextField(blank=True)),
                ('education', MedicalForms.utils.MyTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizationAndDirection',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('TO', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('FROM', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('patient_name', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('automobile_insurer', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('claim_policy_number', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('date_of_loss', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('SIN', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('legal_representative', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('primary_insurer', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('authorize_name', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('patient_signature', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('witness_name', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('witness_signature', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cardiovascular',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cervical',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('neutral_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('neutral_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('jackson_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('jackson_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('spurling_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('spurling_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('hermitte_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('hermitte_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('julls_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('julls_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('adson_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('adson_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('wrights_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('wrights_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('edens_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('edens_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('easts_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('easts_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('doorbell_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('doorbell_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
            ],
        ),
        migrations.CreateModel(
            name='CervicalSpineQuestions',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('intensity', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('duration', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('numbness', MedicalForms.utils.MyNullBooleanField()),
                ('paraesthesia', MedicalForms.utils.MyNullBooleanField()),
                ('aggravated_by_movements', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('relieved_by', MedicalForms.utils.MyNullBooleanField()),
                ('radiation', MedicalForms.utils.MyNullBooleanField()),
                ('pain_location', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('aggravated_by', models.ManyToManyField(to='MedicalForms.AggravatedByOthers', blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChiropracticTreatment',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('signature', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('name', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DateSignature',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('signature_date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('signature', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DischargeReasons',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EarlySign',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Elbow',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('flexion_l', models.IntegerField(blank=True)),
                ('flexion_r', models.IntegerField(blank=True)),
                ('extension_l', models.IntegerField(blank=True)),
                ('extension_r', models.IntegerField(blank=True)),
                ('supination_l', models.IntegerField(blank=True)),
                ('supination_r', models.IntegerField(blank=True)),
                ('pronation_l', models.IntegerField(blank=True)),
                ('pronation_r', models.IntegerField(blank=True)),
                ('cozens_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('cozens_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('reverse_cozens_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('reverse_cozens_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('tinels_elbow_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('tinels_elbow_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('tinels_wrist_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('tinels_wrist_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('varus_stress_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('varus_stress_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('valgus_stress_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('valgus_stress_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyPersonnel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Examinations',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeInformation',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('physician_name', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('physician_address', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('physician_phone', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('physician_fax', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('patient_name', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('patient_dob', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('representative_name1', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('forward_from_name', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('include_notes', MedicalForms.utils.MyNullBooleanField()),
                ('signature', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('representative_name2', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('representative_relationship', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('TO', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('RE', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('patient_signature', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('witness_signature', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gastrointestinal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genitourinary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HeadacheQuestions',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('intensity', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('duration', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('numbness', MedicalForms.utils.MyNullBooleanField()),
                ('paraesthesia', MedicalForms.utils.MyNullBooleanField()),
                ('aggravated_by_movements', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('relieved_by', MedicalForms.utils.MyNullBooleanField()),
                ('aggravated_by', models.ManyToManyField(to='MedicalForms.AggravatedByHeadache', blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthHistory',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('menstrual_flow', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('pregnant', MedicalForms.utils.MyNullBooleanField()),
                ('cnd_disorders', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('current_medications', MedicalForms.utils.MyTextField(blank=True)),
                ('previous_surgeries', MedicalForms.utils.MyTextField(blank=True)),
                ('smoker', MedicalForms.utils.MyNullBooleanField()),
                ('other_conditions', MedicalForms.utils.MyTextField(blank=True)),
                ('family_doctor', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('family_doctor_telephone', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('cardiovascular', models.ManyToManyField(to='MedicalForms.Cardiovascular', blank=True)),
                ('gastrointestinal', models.ManyToManyField(to='MedicalForms.Gastrointestinal', blank=True)),
                ('general', models.ManyToManyField(to='MedicalForms.General', blank=True)),
                ('genitourinary', models.ManyToManyField(to='MedicalForms.Genitourinary', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Knee',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('flexion_l', models.IntegerField(blank=True)),
                ('flexion_r', models.IntegerField(blank=True)),
                ('extension_l', models.IntegerField(blank=True)),
                ('extension_r', models.IntegerField(blank=True)),
                ('internal_rot_l', models.IntegerField(blank=True)),
                ('internal_rot_r', models.IntegerField(blank=True)),
                ('external_rot_l', models.IntegerField(blank=True)),
                ('external_rot_r', models.IntegerField(blank=True)),
                ('varus_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('varus_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('valgus_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('valgus_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('anterior_drawer_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('anterior_drawer_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('posterior_drawer_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('posterior_drawer_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('joint_line_tenderness_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('joint_line_tenderness_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('thesselis_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('thesselis_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('mcmurrays_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('mcmurrays_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('patello_femoral_grind_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('patello_femoral_grind_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('obers_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('obers_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('nobles_comp_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('nobles_comp_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('patellar_comp_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('patellar_comp_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
            ],
        ),
        migrations.CreateModel(
            name='LegsLeftRight',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LocationImpact',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LowerExtremity',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('question_1', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_2', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_3', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_4', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_5', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_6', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_7', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_8', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_9', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_10', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_11', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_12', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_13', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_14', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_15', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_16', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_17', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_18', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_19', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_20', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lumbar',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('slr_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('slr_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('braggarts_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('braggarts_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('bowstring_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('bowstring_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('thomas_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('thomas_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('fig4_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('fig4_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('si_comp_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('si_comp_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('yeomans_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('yeomans_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('hibbs_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('hibbs_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('gillets_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('gillets_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('sorensons_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
            ],
        ),
        migrations.CreateModel(
            name='LumbarSpineQuestions',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('intensity', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('duration', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('numbness', MedicalForms.utils.MyNullBooleanField()),
                ('paraesthesia', MedicalForms.utils.MyNullBooleanField()),
                ('aggravated_by_movements', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('relieved_by', MedicalForms.utils.MyNullBooleanField()),
                ('radiation', MedicalForms.utils.MyNullBooleanField()),
                ('pain_location', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('aggravated_by', models.ManyToManyField(to='MedicalForms.AggravatedByOthers', blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MassageTreatment',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('signature', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('name', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAuthorization',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('TO', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('RE', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('patient_signature', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('witness_signature', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleJoint',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MVAIntake',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('today_date', models.DateTimeField(auto_now_add=True)),
                ('gait', models.CharField(blank=True, max_length=10, choices=[(b'Antalgic', b'Antalgic'), (b'Normal', b'Normal')])),
                ('assistive_devices', models.CharField(max_length=100, blank=True)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NeckDisability',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('question_1', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_2', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_3', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_4', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_5', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_6', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_7', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_8', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_9', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_10', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherConditions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OtherSubjectiveEvaluationQuestions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('conditions', models.ManyToManyField(to='MedicalForms.OtherConditions', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pain',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerLocation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDischarge',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('today_date', models.DateTimeField(auto_now_add=True)),
                ('initial_complaint', MedicalForms.utils.MyTextField(blank=True)),
                ('progress_to_date', MedicalForms.utils.MyTextField(blank=True)),
                ('reccurance_recommendation', MedicalForms.utils.MyTextField(blank=True)),
                ('risks_complications', MedicalForms.utils.MyTextField(blank=True)),
                ('schedule_date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('communication', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('other_notes', MedicalForms.utils.MyTextField(blank=True)),
                ('clinician', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('sign_date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('discharge_reason', models.ManyToManyField(to='MedicalForms.DischargeReasons', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('accident_date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('date_of_birth', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('gender', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('address', MedicalForms.utils.MyCharField(max_length=200, blank=True)),
                ('city', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('postal_code', MedicalForms.utils.MyCharField(max_length=10, blank=True)),
                ('first_language', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('home_phone', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('mobile_phone', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('work_phone', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('occupation', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('modified_duties_availability', MedicalForms.utils.MyNullBooleanField()),
                ('occupational_status', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('job_requirements', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('marital_status', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('number_of_children', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('ages', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('emergency_contact_name', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('emergency_contact_phone', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('emergency_contact_relationship', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('current_complaint_1', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('current_complaint_2', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('current_complaint_3', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('current_complaint_4', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('previous_injury', MedicalForms.utils.MyNullBooleanField()),
                ('previous_injury_detail', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('previous_work_injury', MedicalForms.utils.MyNullBooleanField()),
                ('previous_work_injury_detail', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('previous_sporting_injury', MedicalForms.utils.MyNullBooleanField()),
                ('previous_sporting_injury_detail', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('previous_therapy', MedicalForms.utils.MyNullBooleanField()),
                ('previous_therapy_detail', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('hospitalized', MedicalForms.utils.MyNullBooleanField()),
                ('hospitalized_detail', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('previous_test', MedicalForms.utils.MyNullBooleanField()),
                ('previous_test_detail', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientSpecific',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('date_1', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('date_2', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('date_3', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('date_4', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('date_5', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('activity_1', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('score_1_1', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_1_2', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_1_3', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_1_4', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_1_5', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_1_6', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('activity_2', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('score_2_1', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_2_2', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_2_3', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_2_4', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_2_5', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_2_6', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('activity_3', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('score_3_1', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_3_2', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_3_3', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_3_4', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_3_5', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_3_6', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('activity_4', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('score_4_1', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_4_2', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_4_3', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_4_4', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_4_5', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_4_6', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('activity_5', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('score_5_1', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_5_2', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_5_3', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_5_4', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_5_5', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_5_6', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_additional_1', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_additional_2', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_additional_3', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_additional_4', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_additional_5', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_additional_6', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_average_1', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_average_2', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_average_3', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_average_4', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_average_5', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('score_average_6', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeripheralJointQuestions1',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('radiation', MedicalForms.utils.MyNullBooleanField()),
                ('pain_location', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('aggravated_by', models.ManyToManyField(to='MedicalForms.AggravatedByPeripheralJoint', blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeripheralJointQuestions2',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('radiation', MedicalForms.utils.MyNullBooleanField()),
                ('pain_location', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('aggravated_by', models.ManyToManyField(to='MedicalForms.AggravatedByPeripheralJoint', blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeripheralJointQuestions3',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('radiation', MedicalForms.utils.MyNullBooleanField()),
                ('pain_location', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('aggravated_by', models.ManyToManyField(to='MedicalForms.AggravatedByPeripheralJoint', blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeripheralJointQuestions4',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('radiation', MedicalForms.utils.MyNullBooleanField()),
                ('pain_location', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('aggravated_by', models.ManyToManyField(to='MedicalForms.AggravatedByPeripheralJoint', blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhysiotherapyTreatment',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('signature', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('name', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanOfManagement',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('start_date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('end_date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('ffs_poc', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('poc_detail', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('duration_week', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('for_week', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('acu_mass', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('acu_week', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('acu_for_week', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('diagnosis_1', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('diagnosis_2', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('diagnosis_3', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('diagnosis_4', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('diagnosis_5', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('dob', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('claim_number', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('ice_heat', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('ice_heat_region', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('laser', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('laser_region', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('ultrasound', MedicalForms.utils.MySelectField(max_length=10, blank=True)),
                ('ultrasound_percent', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('ultrasound_w', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('ultrasound_min', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('ultrasound_region', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('ifc', MedicalForms.utils.MySelectField(max_length=30, blank=True)),
                ('ifc_region', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('ems_russian', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('microcurrent', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('bike_time', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('bike_load', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('treadmill_time', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('treadmill_load', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('elliptical_time', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('elliptical_load', MedicalForms.utils.MyIntegerField(null=True, blank=True)),
                ('stt_region', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('mob_region', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('smt_region', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('neck_muscles', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('neck_exercies', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('shoulder_muscles', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('shoulder_exercies', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('forarm_muscles', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('forarm_exercies', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('ts_muscles', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('ts_exercies', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('ls_muscles', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('ls_exercies', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('hip_muscles', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('hip_exercies', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('thigh_muscles', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('thigh_exercies', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('lower_leg_muscles', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('lower_leg_exercies', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('ankle_muscles', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('ankle_exercies', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('core_muscles', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('core_exercies', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('notes', MedicalForms.utils.MyTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresentPain',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousConditions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RedFlags',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Refferal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ReportOfFindings',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_of_assessment', MedicalForms.utils.MyDateField(null=True, blank=True)),
                ('presenting_complaint', MedicalForms.utils.MyTextField(blank=True)),
                ('examination_findings', MedicalForms.utils.MyTextField(blank=True)),
                ('diagnosis', MedicalForms.utils.MyTextField(blank=True)),
                ('plan_of_management', MedicalForms.utils.MyTextField(blank=True)),
                ('goals', MedicalForms.utils.MyTextField(blank=True)),
                ('risks_discussed', MedicalForms.utils.MyTextField(blank=True)),
                ('alternatives', MedicalForms.utils.MyTextField(blank=True)),
                ('prognosis', MedicalForms.utils.MyTextField(blank=True)),
                ('estimated_time_for_recovery', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('patient_questions', MedicalForms.utils.MyTextField(blank=True)),
                ('signature_date', MedicalForms.utils.MyDateField(null=True, blank=True)),
                ('patient_signature', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('clinician_signature', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respiratory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section47',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('patient_name', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('patient_signature', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('witness_name', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('witness_signature', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoulder',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('flexion_l', models.IntegerField(blank=True)),
                ('flexion_r', models.IntegerField(blank=True)),
                ('extension_l', models.IntegerField(blank=True)),
                ('extension_r', models.IntegerField(blank=True)),
                ('abduction_l', models.IntegerField(blank=True)),
                ('abduction_r', models.IntegerField(blank=True)),
                ('internal_rotation_l', models.IntegerField(blank=True)),
                ('internal_rotation_r', models.IntegerField(blank=True)),
                ('external_rotation_l', models.IntegerField(blank=True)),
                ('external_rotation_r', models.IntegerField(blank=True)),
                ('horizontal_abd_l', models.IntegerField(blank=True)),
                ('horizontal_abd_r', models.IntegerField(blank=True)),
                ('horizontal_add_l', models.IntegerField(blank=True)),
                ('horizontal_add_r', models.IntegerField(blank=True)),
                ('scapulocostal_rhythm_l', models.IntegerField(blank=True)),
                ('scapulocostal_rhythm_r', models.IntegerField(blank=True)),
                ('speeds_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('speeds_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('yergasons_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('yergasons_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('empty_can_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('empty_can_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('hornblowers_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('hornblowers_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('hawkins_kennedy_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('hawkins_kennedy_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('neers_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('neers_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('obriens_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('obriens_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('crank_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('crank_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('load_and_shift_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('load_and_shift_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('anterior_apprehension_l', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('anterior_apprehension_r', models.CharField(blank=True, max_length=1, choices=[(b'+', b'+'), (b'-', b'-')])),
                ('main_form', models.OneToOneField(to='MedicalForms.MVAIntake')),
            ],
        ),
        migrations.CreateModel(
            name='ShouldersLeftRight',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatutoryAccidentsBenefits',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('patient_name', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('patient_signature', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('witness_name', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('witness_signature', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ThoracicSpineQuestions',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('intensity', MedicalForms.utils.IntegerRangeField(null=True, blank=True)),
                ('duration', MedicalForms.utils.MyCharField(max_length=20, blank=True)),
                ('numbness', MedicalForms.utils.MyNullBooleanField()),
                ('paraesthesia', MedicalForms.utils.MyNullBooleanField()),
                ('aggravated_by_movements', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('relieved_by', MedicalForms.utils.MyNullBooleanField()),
                ('radiation', MedicalForms.utils.MyNullBooleanField()),
                ('pain_location', MedicalForms.utils.MyCharField(max_length=100, blank=True)),
                ('aggravated_by', models.ManyToManyField(to='MedicalForms.AggravatedByOthers', blank=True)),
                ('present_pain', models.ManyToManyField(to='MedicalForms.PresentPain', blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TMJScreening',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('doi', MedicalForms.utils.MyDateTimeField(null=True, blank=True)),
                ('signature', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('pain_level_1', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('pain_level_2', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('pain_level_3', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('pain_level_4', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('pain_description_1', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('pain_description_2', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('pain_description_3', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('pain_description_4', MedicalForms.utils.MySelectField(max_length=20, blank=True)),
                ('pain_intensity', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('pain', models.ManyToManyField(to='MedicalForms.Pain', blank=True)),
                ('symptom', models.ManyToManyField(to='MedicalForms.Symptom', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('plan_name', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
                ('approved', MedicalForms.utils.MyCharField(max_length=50, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPainHeadache',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPainOthers',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UpperExtremity',
            fields=[
                ('patient', models.OneToOneField(primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('question_1', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_2', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_3', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_4', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_5', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_6', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_7', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_8', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_9', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_10', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_11', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_12', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_13', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_14', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_15', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_16', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_17', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_18', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_19', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
                ('question_20', MedicalForms.utils.MyRadioField(max_length=2, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WomenOnlyChoices',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='patient',
            field=models.ForeignKey(to='MedicalAppointments.Patient'),
        ),
        migrations.AddField(
            model_name='thoracicspinequestions',
            name='type_of_pain',
            field=models.ManyToManyField(to='MedicalForms.TypeOfPainOthers', blank=True),
        ),
        migrations.AddField(
            model_name='peripheraljointquestions4',
            name='type_of_pain',
            field=models.ManyToManyField(to='MedicalForms.TypeOfPainOthers', blank=True),
        ),
        migrations.AddField(
            model_name='peripheraljointquestions3',
            name='type_of_pain',
            field=models.ManyToManyField(to='MedicalForms.TypeOfPainOthers', blank=True),
        ),
        migrations.AddField(
            model_name='peripheraljointquestions2',
            name='type_of_pain',
            field=models.ManyToManyField(to='MedicalForms.TypeOfPainOthers', blank=True),
        ),
        migrations.AddField(
            model_name='peripheraljointquestions1',
            name='type_of_pain',
            field=models.ManyToManyField(to='MedicalForms.TypeOfPainOthers', blank=True),
        ),
        migrations.AddField(
            model_name='othersubjectiveevaluationquestions',
            name='patient',
            field=models.OneToOneField(to='MedicalAppointments.Patient'),
        ),
        migrations.AddField(
            model_name='lumbarspinequestions',
            name='present_pain',
            field=models.ManyToManyField(to='MedicalForms.PresentPain', blank=True),
        ),
        migrations.AddField(
            model_name='lumbarspinequestions',
            name='type_of_pain',
            field=models.ManyToManyField(to='MedicalForms.TypeOfPainOthers', blank=True),
        ),
        migrations.AddField(
            model_name='lumbar',
            name='main_form',
            field=models.OneToOneField(to='MedicalForms.MVAIntake'),
        ),
        migrations.AddField(
            model_name='knee',
            name='main_form',
            field=models.OneToOneField(to='MedicalForms.MVAIntake'),
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='muscle_joint',
            field=models.ManyToManyField(to='MedicalForms.MuscleJoint', blank=True),
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='previous_conditions',
            field=models.ManyToManyField(to='MedicalForms.PreviousConditions', blank=True),
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='respiratory',
            field=models.ManyToManyField(to='MedicalForms.Respiratory', blank=True),
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='skin',
            field=models.ManyToManyField(to='MedicalForms.Skin', blank=True),
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='women_only_choices',
            field=models.ManyToManyField(to='MedicalForms.WomenOnlyChoices', blank=True),
        ),
        migrations.AddField(
            model_name='headachequestions',
            name='present_pain',
            field=models.ManyToManyField(to='MedicalForms.PresentPain', blank=True),
        ),
        migrations.AddField(
            model_name='headachequestions',
            name='type_of_pain',
            field=models.ManyToManyField(to='MedicalForms.TypeOfPainHeadache', blank=True),
        ),
        migrations.AddField(
            model_name='elbow',
            name='main_form',
            field=models.OneToOneField(to='MedicalForms.MVAIntake'),
        ),
        migrations.AddField(
            model_name='datesignature',
            name='patient',
            field=models.ForeignKey(to='MedicalAppointments.Patient'),
        ),
        migrations.AddField(
            model_name='cervicalspinequestions',
            name='present_pain',
            field=models.ManyToManyField(to='MedicalForms.PresentPain', blank=True),
        ),
        migrations.AddField(
            model_name='cervicalspinequestions',
            name='type_of_pain',
            field=models.ManyToManyField(to='MedicalForms.TypeOfPainOthers', blank=True),
        ),
        migrations.AddField(
            model_name='cervical',
            name='main_form',
            field=models.OneToOneField(to='MedicalForms.MVAIntake'),
        ),
        migrations.AddField(
            model_name='acuteconcussionevaluation',
            name='diagnosis',
            field=models.ManyToManyField(to='MedicalForms.Diagnosis', blank=True),
        ),
        migrations.AddField(
            model_name='acuteconcussionevaluation',
            name='doctor',
            field=models.ForeignKey(blank=True, to='MedicalAppointments.Doctor', null=True),
        ),
        migrations.AddField(
            model_name='acuteconcussionevaluation',
            name='early_signs',
            field=models.ManyToManyField(to='MedicalForms.EarlySign', blank=True),
        ),
        migrations.AddField(
            model_name='acuteconcussionevaluation',
            name='location_of_impact',
            field=models.ManyToManyField(to='MedicalForms.LocationImpact', blank=True),
        ),
        migrations.AddField(
            model_name='acuteconcussionevaluation',
            name='red_flags',
            field=models.ManyToManyField(to='MedicalForms.RedFlags', blank=True),
        ),
        migrations.AddField(
            model_name='acuteconcussionevaluation',
            name='refferal',
            field=models.ManyToManyField(to='MedicalForms.Refferal', blank=True),
        ),
        migrations.AddField(
            model_name='accidenthistory',
            name='arms_which',
            field=models.ManyToManyField(to='MedicalForms.ArmsLeftRight', blank=True),
        ),
        migrations.AddField(
            model_name='accidenthistory',
            name='body_part_collision',
            field=models.ManyToManyField(to='MedicalForms.BodyPart', blank=True),
        ),
        migrations.AddField(
            model_name='accidenthistory',
            name='emergency_personnel',
            field=models.ManyToManyField(to='MedicalForms.EmergencyPersonnel', blank=True),
        ),
        migrations.AddField(
            model_name='accidenthistory',
            name='examination_type',
            field=models.ManyToManyField(to='MedicalForms.Examinations', blank=True),
        ),
        migrations.AddField(
            model_name='accidenthistory',
            name='legs_which',
            field=models.ManyToManyField(to='MedicalForms.LegsLeftRight', blank=True),
        ),
        migrations.AddField(
            model_name='accidenthistory',
            name='passengers',
            field=models.ManyToManyField(to='MedicalForms.PassengerLocation', blank=True),
        ),
        migrations.AddField(
            model_name='accidenthistory',
            name='shoulders_which',
            field=models.ManyToManyField(to='MedicalForms.ShouldersLeftRight', blank=True),
        ),
    ]
