# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 14:26
from __future__ import unicode_literals

import MedicalForms.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalForms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='translator_need',
            field=MedicalForms.utils.MyNullBooleanField(),
        ),
    ]
