# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 02:49
from __future__ import unicode_literals

import MedicalForms.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalAppointments', '0001_initial'),
        ('MedicalForms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSatisfactionSurvey',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MedicalAppointments.Patient')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('submitted', MedicalForms.utils.HiddenBooleanField(default=False)),
                ('patient_type', MedicalForms.utils.MyRadioField(blank=True, max_length=10)),
                ('patient_type_other', MedicalForms.utils.MyCharField(blank=True, max_length=30)),
                ('question_1', MedicalForms.utils.MyRadioField(blank=True, max_length=2)),
                ('question_2', MedicalForms.utils.MyRadioField(blank=True, max_length=2)),
                ('question_3', MedicalForms.utils.MyRadioField(blank=True, max_length=2)),
                ('question_4', MedicalForms.utils.MyRadioField(blank=True, max_length=2)),
                ('question_5', MedicalForms.utils.MyRadioField(blank=True, max_length=2)),
                ('question_6', MedicalForms.utils.MyRadioField(blank=True, max_length=2)),
                ('question_7', MedicalForms.utils.MyRadioField(blank=True, max_length=2)),
                ('comments', MedicalForms.utils.MyTextField(blank=True)),
            ],
        ),
    ]
